name: Weekly Badminton Signup

on:
  schedule:
  #  run every Monday at 7pm  UTC
    - cron: '0 19 * * 1'
jobs:
  runApp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Run Selenium tests
      run: |
        source venv/bin/activate
        python main.py
      env:
        DISPLAY: ":99.0"
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}