name: Weekly Badminton Signup

on:
  schedule:
    # Run every 2 minutes
    - cron: '*/2 * * * *'
  # Comment out or remove the push trigger if you don't want it
  # push:
  #   branches:
  #     - main

jobs:
  runApp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          source venv/bin/activate
          python main.py
        env:
          DISPLAY: ":99.0"
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CVV_CODE: ${{ secrets.CVV_CODE }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          DRY_RUN: "true"
